### ISSUE TITLE
no implicit ranges in manual CFF

### ISSUE THREAD

**Issue by lucacioria** [buildo/cashflow#5]
in manual CFF we have to specify ranges explicitely as:

```
expectedDate: ['..', '..']
```

why not have implicit ranges, where a singe values means both min and max?

```
expectedDate: '...'
```

Is this an intended behavior? Is this logic present elsewhere but not applied to the manual CFF?

**Comment by gabro** [comment]
For what is worth I believe

```
expectedDate: ['..']
```

works. I agree it would be nice to a have a shorthand and drop the array syntax altogether.
